#+title: Log.gd Todos

* v0.1.0
** [X] pull in Log.gd from Dothop/dino
CLOSED: [2024-02-16 Fri 17:51]
** [X] create example scene and script that uses it
CLOSED: [2024-02-16 Fri 17:52]
** [X] add gdunit
CLOSED: [2024-02-16 Fri 18:19]
** [X] write some tests
CLOSED: [2024-03-09 Sat 15:55]
** [X] github actions running tests
CLOSED: [2024-03-20 Wed 16:40]
** [X] impl, tests for log() (duck-typing opt-in to pretty printing per object)
CLOSED: [2024-03-20 Wed 17:01]
should be argless
** [X] license
CLOSED: [2024-03-20 Wed 17:45]
** [X] create docs website
CLOSED: [2024-03-21 Thu 15:38]
check out pandora, phantom-cam, gaea's static site tooling
** SKIP github action creating releases
CLOSED: [2024-03-21 Thu 15:38]
** [X] restore call-site module prefix
CLOSED: [2024-03-21 Thu 15:57]
- add line to docs and readme
- update readme/site screenshots
- include line numbers
** [X] write and submit to godot asset library
CLOSED: [2024-03-21 Thu 18:33]
** [X] to_printable naming (vs to_pretty)?
CLOSED: [2024-06-22 Sat 10:01]
** [X] add static typing everywhere
CLOSED: [2025-01-29 Wed 11:40]
** [X] docs for public api
CLOSED: [2025-06-25 Wed 10:43]
*** Log.to_pretty
*** `to_pretty()`, `data()`
*** Log.set_color_scheme(scheme) and related
** [X] readme link, docs install instructions
CLOSED: [2025-06-25 Wed 10:43]
** [X] better public obj -> rich-string function
CLOSED: [2025-06-25 Wed 10:43]
no more wrap it in [] nonsense
** SKIP readme/docs content
CLOSED: [2025-06-25 Wed 10:44]
*** preview (short-version) of docs example page
*** non-Log.gd-based godot printing quick hits
- print, prints, printt, print_rich
- print_verbose

"Don't want to install a whole addon? Here's a godot print helper overview"
*** A/B differences between Log.pr() and print()
for an object, a node, a list, a dictionary
*** features, with code and screenshots
**** pretty-printing primitives
**** pretty-printing arrays and dicts
**** opting-in to prettier/limited classes/objects
#+begin_src gdscript
func to_printable():
    {your=str(value)}
#+end_src
**** call-site prefixes
*** _not_ a production log-to-file helper
but maybe that's a future direction?
*** prior art
** [X] Example scene should have buttons for printing more things
CLOSED: [2025-12-21 Sun 17:12]
the example outputs could also colorize and print the source code - that output might
be a fun sharable version of the tutorial (i.e. the tutorial is all printed via Log.gd)
** SKIP Docs: 'Example' page
CLOSED: [2025-12-21 Sun 17:12]
walk through the ExampleScene.gd
with individual line-by-line output screenshots
** SKIP docs full api page
CLOSED: [2025-12-21 Sun 17:12]
** SKIP call-site prefix test coverage
CLOSED: [2025-12-21 Sun 17:12]
** SKIP comb docs for todos
CLOSED: [2025-12-21 Sun 17:12]
* v0.0.8
** [X] rainbow delimiters
CLOSED: [2025-08-01 Fri 17:33]
** SKIP fix closing [/color] noise
CLOSED: [2025-08-01 Fri 17:33]
already fixed in godot 4.5
** [X] tests covering rainbow delimiters
CLOSED: [2025-08-01 Fri 17:34]
* v0.1.0
** [X] configurable colors and multiple schemas
CLOSED: [2025-08-01 Fri 17:34]
- pretty colors
- terminal-safe colors
- custom color dictionary

done via BYO-LogColorTheme

* v0.3.0
** Named Loggers
*** [X] initial implementation
*** [X] fix stack trace (all point to PrettyLogger:220)
*** [X] use specified color theme
CLOSED: [2025-12-21 Sun 17:13]
*** [ ] remove or support extra @export vars:
- disable colors/force termsafe
- custom timestamp format
*** [ ] move `LoggerFactory` public funcs to Log
i.e. Log.get_logger/load_logger
** BG colors
*** [ ] decision time
settling on filling the line, space before the line
*** [ ] better color examples
** future
*** [ ] react to .tres logger changes while running
color changes, disable/enable, etc
* v1.0.0
** [X] list prior art (other godot asset lib loggers)
CLOSED: [2025-08-01 Fri 17:34]
** [ ] consider csharp support + implementation
** [ ] configurable per-type prettyprint overrides
example: i want to impl a to_printable for PandoraEntities without subclassing it

type->to_printable opts passed in as a dictionary?
ideally written as a config of some kind

but how to read it from a static function?
maybe need to write constants to disk like pandora does?

could read/write from a ~res://log.gd~ for opts.
(this is what gd-plug does, for example)

- specify colors for types
- specify to_printable overrides
  - for eg, a fallback for PandoraEntities

--

this is possible via the registry - but it's not yet documented
** [ ] hide/show logs based on arbitrary categories
https://mastodon.gamedev.place/deck/@brycedixon@peoplemaking.games/112140962069868440
** [ ] hide/show logs based on script name
